/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORTING_H_RPCGEN
#define _SORTING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSIZE 10

struct Array {
	int num[MAXSIZE];
	int size;
};
typedef struct Array Array;


#define PROG_SORT 4148
#define VER_SORT 1

#if defined(__STDC__) || defined(__cplusplus)
#define SORT 1
extern  Array * sort_1(Array *, CLIENT *);
extern  Array * sort_1_svc(Array *, struct svc_req *);
extern int prog_sort_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SORT 1
extern  Array * sort_1();
extern  Array * sort_1_svc();
extern int prog_sort_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Array (XDR *, Array*);
extern  bool_t xdr_Array (XDR *, Array*);

#else /* K&R C */
extern bool_t xdr_Array ();
extern bool_t xdr_Array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORTING_H_RPCGEN */
